
services:
  shelly-cloud-mcp-server:
    image: giogdev/shelly-cloud-mcp-server:latest
    container_name: shelly-cloud-mcp-server
    restart: unless-stopped
    ports:
      - "80:80"
    environment:
      - SHELLY_API_ENDPOINT=${SHELLY_API_ENDPOINT}
      - SHELLY_API_KEY=${SHELLY_API_KEY}
      - DeviceMappingFile=/app/devices.json # Optional, if you have a custom devices.json file to use
      # Optional, if you have a custom devices.json file to use
    volumes:
      - '<your-path>\devices.json:/app/devices.json:ro'
    stdin_open: true
    tty: false

  shelly-api-gateway:
    image: giogdev/shelly-api-gateway:latest
    container_name: shelly-api-gateway
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - SHELLY_API_ENDPOINT=${SHELLY_API_ENDPOINT}
      - SHELLY_API_KEY=${SHELLY_API_KEY}
      - DeviceMappingFile=/app/devices.json # Optional, if you have a custom devices.json file to use
    # Optional, if you have a custom devices.json file to use
    volumes:
      - '<your-path>\devices.json:/app/devices.json:ro'
